--- FAIL: TestGet (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 8 [running]:
testing.tRunner.func1.2({0x5cd2a0, 0xc0000162e8})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x5cd2a0, 0xc0000162e8})
	/usr/local/go/src/runtime/panic.go:838 +0x207
_/sandbox.(*Stack).Get(...)
	/sandbox/main.go:31
_/sandbox.TestGet(0x0?)
	/sandbox/main_test.go:32 +0x170
testing.tRunner(0xc000105860, 0x5f19e0)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL	_/sandbox	0.004s
